spring:
  application:
    name: match-engine

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /

logging:
  level:
    root: INFO
    '[com.eap]': DEBUG
