server:
  port: 8082
  servlet:
    context-path: /match-engine

spring:
  application:
    name: match-engine

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    root: INFO
    '[com.eap]': DEBUG
