spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eapdb?currentSchema=wallet_service
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest  
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true  