server:
  port: 8084

spring:
  application:
    name: eap-ai-client
  
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1
          temperature: 0.7
          top-p: 0.9
          max-tokens: 1000
      connect-timeout: PT30S
      read-timeout: PT2M

eap:
  mcp:
    base-url: http://localhost:8083
    base-path: ""          # 策略1 沒有 base 前綴就留空
    sse-path: /mcp/sse
    message-path: /mcp/message
    timeout-seconds: 60

logging:
  level:
    com.eap.ai: DEBUG
    org.springframework.ai: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
