server:
  port: 8083

spring:
  application:
    name: eap-mcp

  cloud:
    compatibility-verifier:
      enabled: false
  
  # Redis configuration for rate limiting and caching
  data:
    redis:
      host: localhost
      port: 6379
      database: 2  # Use different database from order service
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Spring AI MCP configuration
  ai:
    mcp:
      server:
        enabled: true
        name: "EAP Trading MCP Server"
        version: "1.0.0"
        description: "Model Context Protocol server for EAP electricity trading platform"
        sse-endpoint: /mcp/sse
        sse-message-endpoint: /mcp/message

# External service configurations
eap:
  order-service:
    base-url: http://localhost:8080/eap-order
  
  wallet:
    base-url: http://localhost:8081/eap-wallet
  
  match-engine:
    base-url: http://localhost:8082/match-engine

# MCP Server configuration
mcp:
  server:
    name: "EAP Trading MCP Server"
    version: "1.0.0"
    description: "Model Context Protocol Server for EAP Electricity Trading Platform"
    max-connections: 100
    timeout: 30s
    # MCP 協議端點
    endpoints:
      base-path: "/mcp"
      sse-path: "/sse"
      websocket-path: "/ws"
  
  # Rate limiting configuration
  rate-limit:
    enabled: true
    requests-per-minute: 60
    burst-capacity: 10
  
  # Audit configuration
  audit:
    enabled: true
    log-level: INFO
    include-request-body: true
    include-response-body: false

# Logging configuration
logging:
  level:
    com.eap.mcp: DEBUG
    org.springframework.ai: DEBUG
    feign: DEBUG
    io.modelcontextprotocol: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
