server:
  port: 8081
  servlet:
    context-path: /eap-wallet

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eapdb
    username: admin
    password: admin123
  liquibase:
    enabled: true                               
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: dev                                 
    drop-first: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
  data:
    redis:
      host: localhost
      port: 6379  
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true

logging:
  level:
    '[com.eap.eap_order]': DEBUG
    '[org.springframework.web]': DEBUG
